"""Write lib/data/trial/_secret.dart from a key that lives OUTSIDE the repo.

Why this exists
---------------
The unlock key was committed twice — as XOR fragments in `_secret.dart` and
again, in clear, as FRAG_A/B/C in `generate_codes.py`. The repository is
public, so both were readable at raw.githubusercontent.com by anyone, with no
login. Anyone who found them could mint unlimited valid unlock codes for a
¥29,800 product, permanently: verification is offline and there is no server
that could revoke anything.

Removing the files does not undo that — git history keeps them forever, and
anyone may already have cloned. The only real remedy is to ROTATE to a key
that was never published, and to make sure the new one cannot be committed by
accident. That is what this script is for.

The key lives at ~/.kaitan/codegen.key (raw hex, 32 bytes). It is read by:
  • this script, to emit the Dart the app compiles in
  • tool/generate_codes.py, to sign codes
Neither file contains key material, so the repository can be public.

Usage
-----
    python tool/make_secret.py --init          # first time: make a new key
    python tool/make_secret.py                 # regenerate _secret.dart
    python tool/make_secret.py --show-path     # where the key file lives

Handing the project to someone else
-----------------------------------
Send them ~/.kaitan/codegen.key through a private channel (never the repo, a
ticket, or a chat log), then have them run this script once. The build then
works exactly as it does here.

Rotating again later
--------------------
Bump KEY_VERSION, run --init --force to mint a new key, rebuild, and ship.
Codes signed with an older version stop verifying, so only do it when no
outstanding code needs to keep working.
"""
from __future__ import annotations

import argparse
import os
import secrets
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / 'lib' / 'data' / 'trial' / '_secret.dart'
KEY_PATH = Path(os.path.expanduser('~/.kaitan/codegen.key'))

# Bumped from 1 on 2026-09-15. Version 1's key was public in this repository
# and in its history; any code signed with it must stop working.
KEY_VERSION = 2
KEY_BYTES = 32

TEMPLATE = '''// GENERATED by tool/make_secret.py — DO NOT COMMIT, DO NOT EDIT BY HAND.
//
// This file carries the unlock-code signing key, so it is gitignored. The key
// itself lives at ~/.kaitan/codegen.key, outside the repository, because the
// repository is public and an earlier version of this file published the v1
// key to the world. Run `python tool/make_secret.py` to recreate this file on
// a new machine.
//
// The key is stored as three fragments XORed together rather than as one
// literal. That is obfuscation, not security — anyone with the binary can
// recover it. It only raises the cost of a casual `strings` sweep.

import 'dart:typed_data';

class UnlockSecrets {{
  UnlockSecrets._();

  /// The key version this build accepts. Codes carry their version in the
  /// payload; anything else is refused outright, which is what makes a
  /// rotation actually invalidate the old codes.
  static const int currentVersion = {version};

  static const _fragA = '{a}';
  static const _fragB = '{b}';
  static const _fragC = '{c}';

  static Uint8List keyForVersion(int version) {{
    if (version != currentVersion) {{
      throw StateError('unknown unlock key version: $version');
    }}
    return _xorFragments(_fragA, _fragB, _fragC);
  }}

  static Uint8List _xorFragments(String a, String b, String c) {{
    final ba = _hex(a);
    final bb = _hex(b);
    final bc = _hex(c);
    final out = Uint8List(ba.length);
    for (var i = 0; i < ba.length; i++) {{
      out[i] = ba[i] ^ bb[i] ^ bc[i];
    }}
    return out;
  }}

  static Uint8List _hex(String s) {{
    final out = Uint8List(s.length ~/ 2);
    for (var i = 0; i < out.length; i++) {{
      out[i] = int.parse(s.substring(i * 2, i * 2 + 2), radix: 16);
    }}
    return out;
  }}
}}
'''


def init_key(force: bool) -> None:
    if KEY_PATH.exists() and not force:
        raise SystemExit(
            f'refusing to overwrite an existing key at {KEY_PATH}\n'
            'Every code ever issued from it would stop working. '
            'Pass --force only if that is what you intend.')
    KEY_PATH.parent.mkdir(parents=True, exist_ok=True)
    KEY_PATH.write_text(secrets.token_hex(KEY_BYTES), encoding='utf-8')
    try:                       # best effort; Windows ignores the mode
        os.chmod(KEY_PATH, 0o600)
    except OSError:
        pass
    print(f'new v{KEY_VERSION} key written to {KEY_PATH}')
    print('BACK THIS FILE UP. Losing it means no further codes can be issued')
    print('for builds already in customers\' hands.')


def emit() -> None:
    if not KEY_PATH.exists():
        raise SystemExit(
            f'no key at {KEY_PATH}\n'
            'Run `python tool/make_secret.py --init` to create one, or copy '
            'the key file from whoever holds it.')
    key = bytes.fromhex(KEY_PATH.read_text(encoding='utf-8').strip())
    if len(key) != KEY_BYTES:
        raise SystemExit(f'key must be {KEY_BYTES} bytes, got {len(key)}')

    # Two random fragments; the third is whatever makes the XOR come out right.
    a = secrets.token_bytes(KEY_BYTES)
    b = secrets.token_bytes(KEY_BYTES)
    c = bytes(k ^ x ^ y for k, x, y in zip(key, a, b))
    assert bytes(x ^ y ^ z for x, y, z in zip(a, b, c)) == key

    OUT.write_text(
        TEMPLATE.format(version=KEY_VERSION, a=a.hex(), b=b.hex(), c=c.hex()),
        encoding='utf-8')
    print(f'wrote {OUT.relative_to(ROOT)}  (key version {KEY_VERSION})')


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument('--init', action='store_true',
                    help='mint a new random key before emitting')
    ap.add_argument('--force', action='store_true',
                    help='with --init, replace an existing key')
    ap.add_argument('--show-path', action='store_true')
    args = ap.parse_args()

    if args.show_path:
        print(KEY_PATH)
        return
    if args.init:
        init_key(args.force)
    emit()


if __name__ == '__main__':
    main()
